services:
   drone:
      image: drone/drone:2
      container_name: drone
      restart: always
      ports:
         - 8090:80
         - 443:443
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - /DroneCI
      environment:
         - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
         - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
         - DRONE_RUNNER_CAPACITY=2
         - DRONE_SERVER_HOST= ${DRONE_SERVER_HOST}
         - DRONE_SERVER_PROTO=https
         - DRONE_TLS_AUTOCERT=true
         - DRONE_USER_CREATE=username:${DRONE_USERNAME},admin:true
         - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
